### ISSUE TITLE
Use fstrings instead of strings + format

### ISSUE THREAD

**Issue by heitorPB** [grupy-sanca/curso-python#15]

**Comment by heitorPB** [comment]
@lamenezes, acha é uma boa?

**Comment by lamenezes** [comment]
Eu não sou fã de fstrings, mas acho que é mais fácil para iniciantes6

**Comment by heitorPB** [comment]
Acho bom deixar isso para o futuro. Ainda tem pessoas que usam python 3 que ainda não chegou na versão que tem as fstrings

**Comment by zsinx6** [comment]
Acho que agora já é um bom momento para adicionar fstrings, acho que é interessante ao menos citar no material, e deixar as duas formas. Vou abrir um pr sobre isso.
