### ISSUE TITLE
add section about python

### ISSUE THREAD

**Issue by lamenezes** [grupy-sanca/curso-python#2]
the page should list how python can be used (web, desktop etc.) and show companies that use python (and how it's used by them)

**Comment by heitorPB** [comment]
also, show some scientific uses of python

**Comment by heitorPB** [comment]
It could be in the beginning of the Introdução section, before the comparison of the languages.

**Comment by heitorPB** [comment]
A nice example:
https://github.com/PyLadiesSP/Cursos/blob/master/B%C3%A1sico%20I/B%C3%A1sico%201.pdf
