### ISSUE TITLE
ensinar como listar variáveis usadas

### ISSUE THREAD

**Issue by heitorPB** [grupy-sanca/curso-python#52]
É bem comum ouvir a pergunta _Como vejo todas as variáveis que declarei?_ quando ministramos esse curso. 

Seria legal responder essa pergunta no cap de variáveis:

Se a pessoa estiver usando o shell do python, dá para usar [`dir()`, `local()`, `global()`](https://stackoverflow.com/questions/633127/viewing-all-defined-variables).

Se a pessoa estiver usando iPython, tem dois comandos mágicos para isso: `%who` e `%whos`.

Se a pessoa estiver usando uma IDE, pode ser que exista em algum lugar lá como ver isso.

**Comment by vccolombo** [comment]
Olá @heitorPB 
acho que já pode fechar essa Issue

**Comment by heitorPB** [comment]
Realmente! 

Imaginei que o  PR #60 ia fechar automagicamente aqui. Valew por lembrar!
